const USER_LOGIN = "USER_LOGIN";
const USER_REGISTER = "USER_REGISTER";
const USER_SINGNOUT = "USER_SINGNOUT";
const THUMB_COLLAPSE = "THUMB_COLLAPSE"
export {
  USER_LOGIN,
  USER_REGISTER,
  USER_SINGNOUT,
  THUMB_COLLAPSE
}
