const USER_LOGIN = "USER_LOGIN";
const USER_REGISTER = "USER_REGISTER";
const USER_SINGNOUT = "USER_SINGNOUT";
const THUMB_COLLAPSE = "THUMB_COLLAPSE"
const ADD_FIELD = "ADD_FIELD"
const ADD_EXH_FIELD = "ADD_EXH_FIELD"
const REMOVE_FIELD = "REMOVE_FIELD"
const RESET_FIELD = "RESET_FIELD"
const UPDATE_FIELD = "UPDATE_FIELD"
const RESET_ALLFIELDS = "RESET_ALLFIELDS"
const RESET_EXH_ALLFIELDS = "RESET_EXH_ALLFIELDS"
const GET_WORKS = "GET_WORKS"
const DELETE_WORK = "DELETE_WORK"
const DELETE_NEW = "DELETE_NEW"
const RESET_EXH = "RESET_EXH"
const GET_EXHS = "GET_EXHS"
const DELETE_EXH = "DELETE_EXH"
const GET_EXH = "GET_EXH"
const UPDATE_EXH = "UPDATE_EXH"
const RESET_NEWFORM = "RESET_NEWFORM"
const GET_NEWS = "GET_NEWS"
const GET_NEW = "GET_NEW"
const UPDATE_NEW = "UPDATE_NEW"
const RESET_PUB = "RESET_PUB"
const GET_PUBS = "GET_PUBS"
const DELETE_PUB = "DELETE_PUB"
const GET_PUB = "GET_PUB"
const GET_TEXTS = "GET_TEXTS"
const RESET_TEXT = "RESET_TEXT"
const GET_TEXT = "GET_TEXT"
const DELETE_TEXT = "DELETE_TEXT"
const UPDATE_TEXT = "UPDATE_TEXT"
const UPDATE_TEXTS = "UPDATE_TEXTS"
const HIDDEN = "HIDDEN"
const ISLOCAL = "ISLOCAL"
const UPDATE_DETAIL_IMG = "UPDATE_DETAIL_IMG"
const UPDATE_EXH_DETAIL_IMG = "UPDATE_EXH_DETAIL_IMG"
const UPDATE_DETAILR_COVER = "UPDATE_DETAILR_COVER"
const UPDATE_EXH_DETAILR_COVER = "UPDATE_EXH_DETAILR_COVER"
const UPDATE_EXH_COVER = "UPDATE_EXH_COVER"
const UPDATE_PUB_COVER = "UPDATE_PUB_COVER"
const UPDATE_NEWS_COVER = "UPDATE_NEWS_COVER"
const UPDATE_NEWS = "UPDATE_NEWS"
const CHANGE_LOOP = "CHANGE_LOOP"
const REMOVE_EXH_FIELD = "REMOVE_EXH_FIELD"
export {
  USER_LOGIN,
  USER_REGISTER,
  USER_SINGNOUT,
  THUMB_COLLAPSE,
  ADD_FIELD,
  ADD_EXH_FIELD,
  REMOVE_FIELD,
  REMOVE_EXH_FIELD,
  RESET_FIELD,
  UPDATE_FIELD,
  RESET_ALLFIELDS,
  RESET_EXH_ALLFIELDS,
  GET_WORKS,
  DELETE_WORK,
  RESET_EXH,
  GET_EXHS,
  DELETE_EXH,
  GET_EXH,
  UPDATE_EXH,
  RESET_NEWFORM,
  GET_NEWS,
  GET_NEW,
  DELETE_NEW,
  UPDATE_NEW,
  RESET_PUB,
  GET_PUBS,
  DELETE_PUB,
  GET_PUB,
  RESET_TEXT,
  GET_TEXT,
  DELETE_TEXT,
  UPDATE_TEXT,
  UPDATE_TEXTS,
  HIDDEN,
  ISLOCAL,
  UPDATE_DETAIL_IMG,
  UPDATE_EXH_DETAIL_IMG,
  UPDATE_DETAILR_COVER,
  UPDATE_EXH_DETAILR_COVER,
  UPDATE_EXH_COVER,
  UPDATE_PUB_COVER,
  UPDATE_NEWS_COVER,
  GET_TEXTS,
  UPDATE_NEWS,
  CHANGE_LOOP
}
